### PR TITLE
Updated Getting Started

### PR DESCRIPTION
**Pull request by codelectron**
Added Crossbar arch, More detailed explanation, etc

### CODE REVIEW

**Comment by oberstet** [comment]
@codelectron awesome!! =)

rgd CI failing: https://travis-ci.org/crossbario/crossbar/builds/450613263

the last 2 fails (`TOX_ENV=pypy3-pinned-trial` and `TOX_ENV=py36-pinned-trial`) are "ok" : "pinned" => it tests against pinned / latest release of ABPy, which fails, because there are changes in CB that require AB master changes.

however, this fail is sth you might look into:

https://travis-ci.org/crossbario/crossbar/jobs/450613265#L795

when this latter tests pass, the PR will become mergable, because the 2 failing other tests are not _required_ for the whole PR to become green : https://github.com/crossbario/crossbar/blob/master/.travis.yml#L97

**Comment by oberstet** [comment]
still failing .. now differently;)

https://travis-ci.org/crossbario/crossbar/jobs/451492411#L789

you can test locally by doing: `tox -e sphinx`. see: https://gist.github.com/oberstet/b71d93728fe8b8a0a0626dae50b1adc0

**Comment by codelectron** [comment]
Oh Ya, now the error comes from the markdown to rst converted part, I think it will take some time. 
Thanks for the link :)

**Comment by codelectron** [comment]
fixed the table related issues  :)

**Comment by oberstet** [comment]
awesome! =)

**Pull request merged**
