### PR TITLE
crossbarconnect vanished, using an alternative

### PR DESCRIPTION
**Pull request by brammeleman**
readme.md and code in the referenced example also needs some rewriting...

### CODE REVIEW

**Comment by om26er** [comment]
> readme.md and code in the referenced example also needs some rewriting...

patches welcome :)

Also the change looks good to me and I believe the disappearance of crossbarconnect is a [fact](https://groups.google.com/forum/#!topic/crossbario/6B7SNyFYoWI)

**Comment by om26er** [comment]
Merging as this definitely does not change any functionality and improves an obviously broken doc.

**Comment by oberstet** [comment]
@om26er pls backout this commit and do not merge PR in the future yourself. any contribution here needs to have a CLA signed.

**Comment by om26er** [comment]
> @om26er pls backout this commit and do not merge PR in the future yourself. any contribution here needs to have a CLA signed. https://github.com/crossbario/crossbar/blob/master/CONTRIBUTING.md#contributing-code

sorry about that, I had assumed CLA was for code only, my bad. I created a pull request for the revert. https://github.com/crossbario/crossbar/pull/1213

> additionally, we don't want to link to external code in our docs that suggest the code would come from us (by using "crossbarhttp3" as a name). pls remove the section altogether from the docs

Will do that in a separate PR.

**Pull request merged**
