### PR TITLE
Fix proxy routes when multiple roles configured

### PR DESCRIPTION
**Pull request by om26er**
Fixes https://github.com/crossbario/crossbar/issues/1971

Separately, I think the round robin logic there is completely broken.

### CODE REVIEW

**Comment by om26er** [comment]
> Separately, I think the round robin logic there is completely broken.

What I mean by this is that the existing roundrobin logic assumes that the number of routes is always static. We need to think an alternate approach here because the routes can potentially be dynamic hence it might make sense to have a roundrobin index per realm per role. I can work on that in a follow up branch, if that approach makes sense

**Comment by oberstet** [comment]
> I think the round robin logic there is completely broken.

do you have a unit test that demonstrates that it is broken? without a unit test, broken is undefined, as it works for me: clients can do RPC and PubSub, so what's wrong?

**Comment by om26er** [comment]
Just a clarification, I am talking about the round robin logic inside the ProxyController which decides what proxy route to use for a connection request. This is going to be a difficult task to create an automated test for, do you have any pointers on writing automated tests for this stuff of features in Crossbar ?

And regarding the PR, there is a crossbar config in issue https://github.com/crossbario/crossbar/issues/1971, which makes the relevant bug 100% reproducible.

**Comment by oberstet** [comment]
> do you have any pointers on writing automated tests for this stuff of features in Crossbar 

yes, in this repo in the test folder

**Pull request merged**
