### PR TITLE
don't actually log these failures

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by hawkowl** [comment]
cc @oberstet, good to go when the statuses are green

**Comment by oberstet** [comment]
Cool, this is improving things! Here my review.

Smallish:

1. Maybe use `_set_common_headers` throughout (well, where it may apply) instead of having the respective code "duplicated" (one place to maintain is better)
2. [This](https://github.com/hawkowl/crossbar/blob/a30e857069bfd45614fc356517d38d18d70c5f16/crossbar/adapter/rest/caller.py#L57) is more robust than [this](https://github.com/hawkowl/crossbar/blob/a30e857069bfd45614fc356517d38d18d70c5f16/crossbar/adapter/rest/publisher.py#L56) - please use the former for both

Important:

1. Please test that in all errors thrown from [this](https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/wamp/rpc/errors/backend.py) example app code, the caller endpoint returns a 200 with an `{"error": .., }` including the respective `args` and `kwargs` with error payload
2. In the docs for the HTTP bridge: could we have a complete description of the expected behavior of the bridge rgd the "HTTP level" .. in particular status codes and such. The bridge is part of the public API of CB, and it isn't spec'ed anywhere. See also: http://crossbar.io/docs/Compatibility-Policy/ (where the HTTP bridge isn't mentioned, but it should be)

**Comment by hawkowl** [comment]
Thanks @oberstet, I'll fix these up and reopen it + CC you when it's ready :)

**Comment by hawkowl** [comment]
Reopening so that Travis will do its thing...

**Comment by hawkowl** [comment]
@oberstet I've fixed small points 1 (which should fix https://github.com/crossbario/crossbar/issues/785 ? ) and 2 (so I believe this should fix https://github.com/crossbario/crossbar/issues/786 too? I need to write a test-case for that), and important point 1. Important point 2 I will do in a followup PR and file a new issue, since this diff is getting pretty big.

**Pull request merged**
