### PR TITLE
Improved `isinstance` check

### PR DESCRIPTION
**Pull request by schoonc**

### CODE REVIEW

**Comment by meejah** [comment]
+1, looks good to me
Thanks for the patch :)

**Comment by oberstet** [comment]
@schoonc thanks! as this is your first contribution, before merging, please see here (we need a CAA) http://crossbar.io/docs/Contributing-to-the-project/

**Comment by oberstet** [comment]
@schoonc we've received your CAA, thanks for the patch!

**Comment by oberstet** [comment]
the patch has broken pep8:

```
(python279_1)oberstet@thinkpad-t430s:~/scm/crossbar/crossbar$ make flake8
flake8 --ignore=E501,N801,N802,N803,N805,N806 crossbar
crossbar/router/session.py:205:17: E123 closing bracket does not match indentation of opening bracket's line
make: *** [flake8] Fehler 1
```

but travis was green on the patch before, but not now. strange.

**Comment by schoonc** [comment]
Sorry. I tried to fix it https://github.com/crossbario/crossbar/pull/478.

**Pull request merged**
