### PR TITLE
HTTP Webhook service

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by oberstet** [comment]
what's this? what's the purpose?

**Comment by oberstet** [comment]
is this for https://github.com/crossbario/crossbar/issues/258 ?

**Comment by hawkowl** [comment]
Yes - work in progress for now, need to write up the docs tomorrow. Going to do up an example of driving WAMP messages though github webhooks. If you're happy with the code, feel free to merge it, I just didn't flag it because it didn't have docs :)
On 18 Aug 2015 5:35 pm, Tobias Oberstein <notifications@github.com> wrote:is this for #258 ?

**Comment by hawkowl** [comment]
This is looking better now.

**Comment by oberstet** [comment]
cool! the possibility to consume Web hooks out of the box is neat!

**Pull request merged**
