### PR TITLE
Pins pytrie dependency (1819)

### PR DESCRIPTION
**Pull request by henxing**
[PyTrie](https://pypi.org/project/PyTrie/) version 0.4.0 removes python 2 support, this restricts
valid versions of the pytrie module to `pytrie>=0.3, <0.4.0`.

### CODE REVIEW

**Comment by oberstet** [comment]
crossbar does not support python 2

https://github.com/crossbario/crossbar/blob/5aa0682c6ef1edee8ede920873e16571bf4e68a6/setup.py#L105

so using pytrie 0.4 is fine

**Comment by oberstet** [comment]
btw: thanks for CAA we received!

also, I had a look at the CI run for the last crossbar release

https://travis-ci.com/github/crossbario/crossbar/jobs/369843467#L380

and that seems to still had run PyTrie 0.3.1

are you saying you have run into a problem with pytrie 0.4 on python 3. if so, then we need to examine that definitely! however, as said, crossbar does not support python 2 (it did very long ago ..)

**Comment by henxing** [comment]
My mistake @oberstet, I was under the impression that it did support Python 2. Issue #1819 was noticed while running against Python 2, I assume it isn’t an issue for Python 3.

**Comment by henxing** [comment]
@oberstet one comment, the [installation docs](https://crossbar.io/docs/Installation-on-Linux/) still reference Python 2.7, maybe those should be updated?

**Pull request closed without merging**
