### PR TITLE
guard _router being None

### PR DESCRIPTION
**Pull request by meejah**
I think it would be possible to hit this other ways (e.g. client-TLS cert failing to verify) but I didn't check that.

### CODE REVIEW

**Comment by oberstet** [comment]
So this is a defensive move, or did you actually run into this?

**Comment by meejah** [comment]
I ran into it: if the onChallenge throws e.g. a syntax error or similar then you're in a state where _router is None, but onLeave still gets called (it's still None because a Hello never went out to make it non-None). Maybe this isn't the right solution and I should file a bug for that case?

**Comment by oberstet** [comment]
Oh, I see. I think the change here is then perfectly fine, because it is straight forward, and less complex than getting control over all edges cases of session lifecycle. merging ..

**Comment by meejah** [comment]
The reason I thought TLS might be affected too is because (at least in Twisted) you get `onConnect` but then might get disconnected nearly immediately with certificate verification errors. That is, with an invalid cert you'll still get onConnect always...

**Comment by oberstet** [comment]
Actually, I might have run into this with https://github.com/crossbario/crossbar-examples/tree/master/authentication/tls (invalid cert triggers a traceback)

I was going over many of the examples yesterday before release, but it is daunting now. I only tried so an so many. Hence, yeah, absolutely, better be defensive than sorry;)

**Pull request merged**
