### PR TITLE
Issue844 shutdown

### PR DESCRIPTION
**Pull request by meejah**
This fixes the checks for the 'shutdown' option and adds some documentation (see #844)

### CODE REVIEW

**Comment by meejah** [comment]
Hmm, not sure what's up with Travis -- works with `tox` locally but looks like it can't find coverage-data on travis...

**Comment by oberstet** [comment]
This is certainly a bug, and the PR looks good to me! Why does Travis fail .. no clue .. but the repo is configured to only allow merging when green =(

**Comment by meejah** [comment]
Okay, I'm looking into what's different with travis versus just running "tox" locally...

**Comment by meejah** [comment]
Looks like something with the new coverage 4.2 release (also, I learned that coverage has a C-extension?!)

For now, this pins to `<4.2` if you merge it .. I will figure out what's different though.

**Comment by meejah** [comment]
okay, we don't have to pin version, must pass `--append` to `coverage combine`

**Pull request merged**
