### PR TITLE
prevent value error

### PR DESCRIPTION
**Pull request by voidfuture**

### CODE REVIEW

**Comment by oberstet** [comment]
Oh, good catch!

Would merge right away, but we need a CAA: https://github.com/crossbario/crossbar/wiki/Contributing-to-the-project

Sorry for the hassle .. needs only be done once though ..

**Comment by voidfuture** [comment]
@oberstet sure... just sent over

**Comment by oberstet** [comment]
got it! thx .. also for the fx!

**Comment by voidfuture** [comment]
happy to contribute

**Pull request merged**
