### PR TITLE
Configurable cookie headers  #issue-1511

### PR DESCRIPTION
**Pull request by dshymanskyi-vivasg**
Added functionality to set cookie headers in node config. 
Related to this [issue](https://github.com/crossbario/crossbar/issues/1511)

### CODE REVIEW

**Comment by oberstet** [comment]
thanks for the PR! looked into it: this adds the general ability to set HTTP cookie headers from the config file. the issue you linked is about a new boolean option `http_only` in the config, that when enabled will add `;HttpOnly` to the end value returned by `self.factory._cookiestore.create()` .. which is different;)

**Comment by dshymanskyi-vivasg** [comment]
Sorry for late response. Maybe I misunderstood you, but when i read your comment to issue:
> it would be trivial to add 2 lines to set HttpOnly, SameSite and such - however, we might want to have knobs to control setting of these headers in the node config - so it will be "a couple of lines" instead of just 2.
I thought about what i did in this pull request 

For example if you set in config.json for websocket transport
`

      "type": "websocket",
      "cookie": {
           "store": {
                "type": "file",
                "filename": "cookies.dat"
            },
            "headers": {
                "HttpOnly": true,
                "SameSite": "Strict"
           }
`

to end of cookies will be added ";HttpOnly;SameSite=Strict;"

**Comment by oberstet** [comment]
> For example if you set in config.json for websocket transport

yes, I understand that. it would also allow `"Foobar": "23"`. we don't want that flexibility. we want exactly 1 additional **bit** in the config: http_strict yes/no with default no

**Comment by dshymanskyi-vivasg** [comment]
Left only "http_strict" and "same_site" cookie headers. 
Now its like
`

      "type": "websocket",
      "cookie": {
           "store": {
                "type": "file",
                "filename": "cookies.dat"
            },
            "http_strict": true,
            "same_site": "Strict" // Can only be one of 'Strict'|'Lax'|'None'
      }
`

**Comment by oberstet** [comment]
yeah, this looks great! thanks for the changes.

so let's take this chance and really nail this. I have reread through

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

it seems, there are actually 3 modifiers we might want a user to enable?

* SameSite
* HttpOnly
* Secure

if you agree, how about

```
   'secure': (False, [bool]),
   'http_only': (False, [bool]),
   'same_site': (False, [str])
```

for the node config? that way, there is a direct correspondence between configuration option name and HTTP cookie header modifier name.

in my eyes, ^ is desirable, and then this change also covers all options ..

**Comment by dshymanskyi-vivasg** [comment]
Added secure modifier, but what confuse me the most and main reason why i didn't add secure modifier in previous commit was this comment in code
https://github.com/crossbario/crossbar/blob/1e18ceef1b444f60bca118cd5e57eb7ffbd8f2bf/crossbar/router/cookiestore.py#L134

**Comment by oberstet** [comment]
> do NOT add the "secure" cookie attribute! "secure" refers to the scheme of the Web page that triggered the WS, not WS itself!!

mmh, yeah. not sure anymore;) let's see. the option is harmless since it needs to be activated explicitly

**Comment by dshymanskyi-vivasg** [comment]
Well... let it be then :) Thanks for your time and for merge :)

**Pull request merged**
