### PR TITLE
Update Container-Configuration.rst

### PR DESCRIPTION
**Pull request by antonymott**
New example illustrating container component and router component

### CODE REVIEW

**Comment by oberstet** [comment]
awesome! highly welcome=) thanks for contributing. just one minor thing:

```
sphinx.errors.SphinxWarning: /home/travis/build/crossbario/crossbar/docs/Container-Configuration.rst:56:Content block expected for the "code" directive; none found.
```

the indent is missing I think ..

**Comment by antonymott** [comment]
Having a tough time fixing indentation issues, and each of the four new code blocks file passes indentation test in Atom. I've tried 5 times to fix, but when pasted into github page, fails Travis. If anyone can see what I am doing wrong I'd be happy to try again.

**Comment by oberstet** [comment]
I fixed the issue on this PR https://github.com/crossbario/crossbar/pull/1681 - originally, this PR had also preserved you as author in the commits, by I had to rename the new file, since there was an existing one of the same name. Let me know: we can either merge my PR as is, or you can create a completely new PR and copy over the files from my PR ..

**Comment by antonymott** [comment]
Thanks for fixing and for asking if I need to be preserved as author...seems easiest to simply merge your working #1681. Anyway, it's likely that I'll tweak/improve the example as my production experience with containers/IoT grows. Can you please tell me what I was doing to fail Travis CI every time around the first code block?, as I need to avoid making the same mistake(s) again on my future commits.

**Comment by oberstet** [comment]
Ok, thanks! I merged #1681 and will close thise one. Basically the issue was the missing

```
.. code-block:: json
    {
```

and indentation for the respective code examples (I adjusted the language type pre-block). as sphinx didn't encounter the initial opening `.. code-block` directive, it got confused trying to parse subsequent lines of code ..

**Comment by oberstet** [comment]
ah, one more thing I used .. testing/building locally.

Run docs tests locally:


```
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ tox -e sphinx
GLOB sdist-make: /home/oberstet/scm/crossbario/crossbar/setup.py
sphinx inst-nodeps: /home/oberstet/scm/crossbario/crossbar/.tox/.tmp/package/1/crossbar-20.1.1.zip
sphinx installed: alabaster==0.7.12,appdirs==1.4.3,argh==0.26.2,argon2-cffi==19.2.0,attrs==19.3.0,autobahn==20.1.2,Automat==0.8.0,Babel==2.8.0,bandit==1.6.2,bcrypt==3.1.7,bitstring==3.1.6,cbor==1.0.0,cbor2==4.2.0,certifi==2019.11.28,cffi==1.13.2,chardet==3.0.4,Click==7.0,colorama==0.4.3,constantly==15.1.0,coverage==5.0.3,crossbar==20.1.1,cryptography==2.8,docutils==0.16,entrypoints==0.3,filelock==3.0.12,flake8==3.7.9,flatbuffers==1.11,gitdb2==2.0.6,GitPython==3.0.5,h2==3.1.1,hashin==0.14.6,hpack==3.0.0,hyperframe==5.2.0,hyperlink==19.0.0,idna==2.5,imagesize==1.2.0,importlib-metadata==1.4.0,incremental==17.5.0,Jinja2==2.10.3,lmdb==0.98,MarkupSafe==1.1.1,mccabe==0.6.1,mistune==0.8.4,mock==3.0.5,more-itertools==8.1.0,msgpack==0.6.2,netaddr==0.7.19,numpy==1.15.4,packaging==20.0,passlib==1.7.2,pathtools==0.1.2,pbr==5.4.4,pip-api==0.0.13,pip-licenses==2.0.1,pluggy==0.13.1,priority==1.3.0,psutil==5.6.7,PTable==0.9.2,py==1.8.1,py-ubjson==0.14.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycodestyle==2.5.0,pycparser==2.19,pyenchant==2.0.0,pyflakes==2.1.1,Pygments==2.5.2,PyHamcrest==2.0.0,PyNaCl==1.3.0,pyOpenSSL==19.1.0,pyparsing==2.4.6,PyQRCode==1.2.1,python-snappy==0.5.4,PyTrie==0.3.1,pytz==2019.3,PyYAML==5.3,requests==2.22.0,scour==0.37,sdnotify==0.3.2,service-identity==18.1.0,setproctitle==1.1.10,six==1.14.0,smmap2==2.0.5,snowballstemmer==2.0.0,sortedcontainers==2.1.0,Sphinx==1.8.5,sphinx-rtd-theme==0.4.3,sphinxcontrib-images==0.8.0,sphinxcontrib-spelling==4.3.0,sphinxcontrib-websupport==1.1.2,stevedore==1.31.0,toml==0.10.0,towncrier==19.2.0,tox==3.14.3,treq==18.6.0,Twisted==19.10.0.dev0,txaio==18.8.1,txtorcon==19.1.0,u-msgpack-python==2.5.2,ujson==1.35,urllib3==1.24.3,virtualenv==16.7.9,vmprof==0.4.15,watchdog==0.9.0,Werkzeug==0.16.0,wsaccel==0.6.2,zipp==1.0.0,zlmdb==19.11.1,zope.interface==4.7.1
sphinx run-test-pre: PYTHONHASHSEED='1472196208'
sphinx run-test: commands[0] | pip install --force-reinstall 'urllib3<1.25,>=1.21.1'
Collecting urllib3<1.25,>=1.21.1
  Using cached https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl
Installing collected packages: urllib3
  Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
Successfully installed urllib3-1.24.3
sphinx run-test: commands[1] | sphinx-build -nWT -b dummy ./docs ./docs/_build
Sphinx v1.8.5 in Verwendung
Lade Übersetzungen [en]…erledigt
Initializing Spelling Checker
...
copying static files... done
copying extra files... erledigt
dumping search index in English (code: en) ... erledigt
dumping object inventory... erledigt
build abgeschlossen.

The HTML pages are in docs/_build.
sphinx run-test: commands[4] | -rm -rf /home/oberstet/crossbar-docs
sphinx run-test: commands[5] | cp -R ./docs/_build /home/oberstet/crossbar-docs
_____________________________________________________________________________________________________________________________________ summary _____________________________________________________________________________________________________________________________________
  sphinx: commands succeeded
  congratulations :)
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ 
```

Build docs locally:

```
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ make docs
cd docs && sphinx-build -b html . _build
Sphinx v1.8.5 in Verwendung
Lade Übersetzungen [en]…erledigt
Initializing Spelling Checker
Lade pickle Umgebung...erledigt
/home/oberstet/cpy374_1/lib/python3.7/site-packages/sphinxcontrib/images.py:320: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info('Initiated sphinxcontrib-images backend: ', nonl=True)
Initiated sphinxcontrib-images backend: /home/oberstet/cpy374_1/lib/python3.7/site-packages/sphinxcontrib/images.py:322: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  ':' + backend.__class__.__name__)))
`sphinxcontrib_images_lightbox2.lightbox2:LightBox2`
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 136 source files that are out of date
updating environment: [config changed] 136 added, 1 changed, 0 removed
reading sources... [100%] tutorials-recipe                                                                                                                                                                                                                                         
Copying static files for sphinxcontrib-images...[100%] lightbox2/img/loading.gif                                                                                                                                                                                                   
looking for now-outdated files... none found
pickling environment... erledigt
checking consistency... erledigt
preparing documents... erledigt
writing output... [100%] tutorials-recipe                                                                                                                                                                                                                                          
generating indices... genindex
writing additional pages... search
copying images... [100%] assets/helloworldrpc.svg                                                                                                                                                                                                                                  
copying static files... done
copying extra files... erledigt
dumping search index in English (code: en) ... erledigt
dumping object inventory... erledigt
build abgeschlossen.

The HTML pages are in _build.
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ 
```

**Pull request closed without merging**
