### PR TITLE
Add a snapcraft (https://snapcraft.io) badge

### PR DESCRIPTION
**Pull request by evandandrea**
Congrats on the snap of crossbar :) Here's a badge to show the current build status.

### CODE REVIEW

**Comment by oberstet** [comment]
Thanks Evan!

**Comment by oberstet** [comment]
@evandandrea as I got your attention here, one question we couldn't find an answer yet: we would like to trigger a builds on snapcraft like this:

* automatically trigger a snapcraft build and publish to the **edge channel** when *new commits* arrive on our master branch here
* automaticall trigger a snapcraft build and publish to the **stable channel** when a *new tag* is created on our master branch

Background: Crossbar.io releases are properly tagged on the master branch, and only these should go into the stable channel

> another Q: are you planning support for arm64 (aarch64)?

**Comment by evandandrea** [comment]
Hi @oberstet !

>automaticall trigger a snapcraft build and publish to the stable channel when a new tag is created on our master branch

By policy we don't allowed automated releases into the stable channel. The expectation being that some human QA occurs before end users receive the update. I can't change this policy myself, but you're absolutely welcome to raise it with the snapd architects on https://forum.snapcraft.io (I'm "evan" on there).

>another Q: are you planning support for arm64 (aarch64)? arm64 is quickly gaining interest in embedded (but also in data center) deployments of Crossbar.io

Yes, absolutely! We actually support a lot of architectures underneath build.snapcraft.io, but we're just waiting for [snapcraft.yaml support for specifying build architectures](https://forum.snapcraft.io/t/snapcraft-build-on-hint-for-builders/939) (also tracked in https://github.com/canonical-websites/build.snapcraft.io/issues/819) to turn them on.

**Comment by om26er** [comment]
Thanks Evan, I opened a discussion on forum.snapcraft.io, please look [here](https://forum.snapcraft.io/t/build-snapcraft-should-allow-auto-release-to-stable-when-a-new-release-is-tagged/1476)

**Comment by tim-sueberkrueb** [comment]
Wow, just learned crossbar has a snap now, awesome <3

**Pull request merged**
