### PR TITLE
fix issue #798

### PR DESCRIPTION
**Pull request by slav0nic**

### CODE REVIEW

**Comment by meejah** [comment]
I haven't looked at the one builder failure too closely (looks like some install problem?) but we'd need a signed CAA release from you to merge crossbar chages; see https://github.com/crossbario/crossbar/blob/master/legal/individual_caa.pdf or https://github.com/crossbario/crossbar/tree/master/legal

**Comment by slav0nic** [comment]
i signed CAA 1w ago
master build broken too

**Comment by meejah** [comment]
Ah, okay sorry, your username must not have been added to the list in master yet ... Not too worried about the build failure, it looks unrelated to this anyway.

**Comment by goeddea** [comment]
@meejah - My bad about the contributors list. I've updated this to include @slav0nic

**Comment by meejah** [comment]
I rebased this onto master and merged it as https://github.com/crossbario/crossbar/pull/915

**Pull request closed without merging**
