### PR TITLE
type of .signaure should be unicode

### PR DESCRIPTION
**Pull request by meejah**
Elsewhere we always demand that the signature is unicode.

### CODE REVIEW

**Comment by oberstet** [comment]
@meejah I believe this might have overlapped with https://github.com/crossbario/crossbar/pull/449 .. can't work on it right now, but asked @hawkowl to take a look ..

**Comment by hawkowl** [comment]
I am not sure that it should be Unicode -- a signature is a signed hash (or similar), which is a bunch of encoded bytes. I think `onChallenge` might need to be updated instead? (although it's a WAMP thing so is always unicode anyway? hmm).

**Comment by meejah** [comment]
Yeah, intuitively it seemed to me it should also be ``bytes`` (which I why I assert()-ed that in the original PR). It's entirely possible to instead insist that the signature should be ``bytes``, but that's more changes (and e.g. would change what user-code is supposed to return from ``onChallenge``)...@oberstet?

In either case, I can re-base this and re-push (or re-do it as "signatures are bytes too").

**Comment by oberstet** [comment]
@meejah can we close this PR (as other stuff has been merged already)?

**Comment by meejah** [comment]
yes, should be closed I believe.

**Pull request closed without merging**
