### PR TITLE
prepare for v21.11.1

### PR DESCRIPTION
**Pull request by oberstet**

### CODE REVIEW

**Comment by oberstet** [comment]
in a completely newly built cpy3.10 and fresh venv:

```
  Building wheel for vmprof (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/oberstet/scm/crossbario/crossbar/vers/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1rh9jwvm/vmprof/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1rh9jwvm/vmprof/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-wvqhn72e --python-tag cp310
       cwd: /tmp/pip-install-1rh9jwvm/vmprof/
  Complete output (216 lines):
  running bdist_wheel
  running build
  running build_py
  checking build system type... x86_64-pc-linux-gnu
  checking host system type... x86_64-pc-linux-gnu
  checking target system type... x86_64-pc-linux-gnu
  checking for gcc... gcc
  checking for C compiler default output file name... a.out
  checking whether the C compiler works... yes
  checking whether we are cross compiling... no
  checking for suffix of executables...
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking how to run the C preprocessor... gcc -E
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking minix/config.h usability... no
  checking minix/config.h presence... no
  checking for minix/config.h... no
  checking whether it is safe to define __EXTENSIONS__... yes
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  /bin/sh: /tmp/pip-install-1rh9jwvm/vmprof/src/libbacktrace/missing: No such file or directory
  configure: WARNING: `missing' script is too old or missing
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... yes
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking for gcc... (cached) gcc
  checking whether we are using the GNU C compiler... (cached) yes
  checking whether gcc accepts -g... (cached) yes
  checking for gcc option to accept ISO C89... (cached) none needed
  checking for ranlib... ranlib
  checking for gawk... (cached) gawk
  checking how to print strings... printf
  checking for a sed that does not truncate output... /bin/sed
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking whether the shell understands some XSI constructs... yes
  checking whether the shell understands "+="... yes
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for ar... ar
  checking for strip... strip
  checking for ranlib... (cached) ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  checking unwind.h usability... yes
  checking unwind.h presence... yes
  checking for unwind.h... yes
  checking for _Unwind_Backtrace... yes
  checking for -funwind-tables option... yes
  checking for -frandom-seed=string option... yes
  checking whether gcc supports -W... yes
  checking whether gcc supports -Wall... yes
  checking whether gcc supports -Wwrite-strings... yes
  checking whether gcc supports -Wstrict-prototypes... yes
  checking whether gcc supports -Wmissing-prototypes... yes
  checking whether gcc supports -Wold-style-definition... yes
  checking whether gcc supports -Wmissing-format-attribute... yes
  checking whether gcc supports -Wcast-qual... yes
  checking for _Unwind_GetIPInfo... yes
  checking __sync extensions... yes
  checking __atomic extensions... yes
  checking output filetype... elf64
  looking for a compliant stdint.h in stdint.h, checking for uintmax_t... yes
  checking for uintptr_t... yes
  checking for int_least32_t... yes
  checking for int_fast32_t... yes
  checking for uint64_t... yes
  checking what to include in gstdint.h... stdint.h (already complete)
  checking sys/mman.h usability... yes
  checking sys/mman.h presence... yes
  checking for sys/mman.h... yes
  checking for mmap... yes
  checking link.h usability... yes
  checking link.h presence... yes
  checking for link.h... yes
  checking for dl_iterate_phdr... yes
  checking for fcntl... yes
  checking whether strnlen is declared... yes
  checking for getexecname... no
  checking whether tests can run... yes
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating backtrace-supported.h
  config.status: creating config.h
  config.status: config.h is unchanged
  config.status: executing libtool commands
  sed: can't read ./ltmain.sh: No such file or directory
  sed: can't read ./ltmain.sh: No such file or directory
  mv: cannot stat 'libtoolT': No such file or directory
  cp: cannot stat 'libtoolT': No such file or directory
  chmod: cannot access 'libtool': No such file or directory
  config.status: executing gstdint.h commands
  config.status: executing default commands
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/vmprof
  copying vmprof/stats.py -> build/lib.linux-x86_64-3.10/vmprof
  copying vmprof/__init__.py -> build/lib.linux-x86_64-3.10/vmprof
  copying vmprof/show.py -> build/lib.linux-x86_64-3.10/vmprof
  copying vmprof/reader.py -> build/lib.linux-x86_64-3.10/vmprof
  copying vmprof/upload.py -> build/lib.linux-x86_64-3.10/vmprof
  copying vmprof/profiler.py -> build/lib.linux-x86_64-3.10/vmprof
  copying vmprof/cli.py -> build/lib.linux-x86_64-3.10/vmprof
  copying vmprof/__main__.py -> build/lib.linux-x86_64-3.10/vmprof
  creating build/lib.linux-x86_64-3.10/vmshare
  copying vmshare/__init__.py -> build/lib.linux-x86_64-3.10/vmshare
  copying vmshare/service.py -> build/lib.linux-x86_64-3.10/vmshare
  copying vmshare/binary.py -> build/lib.linux-x86_64-3.10/vmshare
  creating build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/__init__.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/marks.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/query.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/upload.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/merge_point.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/objects.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/constants.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/prettyprinter.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/__main__.py -> build/lib.linux-x86_64-3.10/jitlog
  copying jitlog/parser.py -> build/lib.linux-x86_64-3.10/jitlog
  running build_ext
  building '_vmprof' extension
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/src
  creating build/temp.linux-x86_64-3.10/src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/_vmprof.c -o build/temp.linux-x86_64-3.10/src/_vmprof.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  src/_vmprof.c: In function ‘emit_code_object’:
  src/_vmprof.c:68:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     68 |     co_name = PyUnicode_AsUTF8(co->co_name);
        |             ^
  src/_vmprof.c:71:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     71 |     co_filename = PyUnicode_AsUTF8(co->co_filename);
        |                 ^
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/compat.c -o build/temp.linux-x86_64-3.10/src/compat.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/backtrace.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/backtrace.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/dwarf.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/dwarf.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/elf.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/elf.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/fileline.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/fileline.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/mmap.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/mmap.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/mmapio.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/mmapio.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/posix.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/posix.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/sort.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/sort.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/libbacktrace/state.c -o build/temp.linux-x86_64-3.10/src/libbacktrace/state.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/machine.c -o build/temp.linux-x86_64-3.10/src/machine.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/symboltable.c -o build/temp.linux-x86_64-3.10/src/symboltable.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/oberstet/scm/crossbario/crossbar/vers/include -I/home/oberstet/cpy310/include/python3.10 -c src/vmp_stack.c -o build/temp.linux-x86_64-3.10/src/vmp_stack.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 -I src/ -I src/libbacktrace
  In file included from /home/oberstet/cpy310/include/python3.10/bytesobject.h:62,
                   from /home/oberstet/cpy310/include/python3.10/Python.h:95,
                   from src/vmprof.h:6,
                   from src/vmp_stack.h:3,
                   from src/vmp_stack.c:1:
  src/vmp_stack.c: In function ‘_write_python_stack_entry’:
  src/vmp_stack.c:102:47: error: ‘PyCodeObject’ {aka ‘struct PyCodeObject’} has no member named ‘co_lnotab’
    102 |         lnotab = PyStr_AS_STRING(frame->f_code->co_lnotab);
        |                                               ^~
  /home/oberstet/cpy310/include/python3.10/cpython/bytesobject.h:33:53: note: in definition of macro ‘PyBytes_AS_STRING’
     33 |                                 (((PyBytesObject *)(op))->ob_sval))
        |                                                     ^~
  src/vmp_stack.c:102:18: note: in expansion of macro ‘PyStr_AS_STRING’
    102 |         lnotab = PyStr_AS_STRING(frame->f_code->co_lnotab);
        |                  ^~~~~~~~~~~~~~~
  In file included from /home/oberstet/cpy310/include/python3.10/Python.h:87,
                   from src/vmprof.h:6,
                   from src/vmp_stack.h:3,
                   from src/vmp_stack.c:1:
  src/vmp_stack.c:108:52: error: ‘PyCodeObject’ {aka ‘struct PyCodeObject’} has no member named ‘co_lnotab’
    108 |             len = (int)PyStr_GET_SIZE(frame->f_code->co_lnotab);
        |                                                    ^~
  /home/oberstet/cpy310/include/python3.10/object.h:121:47: note: in definition of macro ‘_PyVarObject_CAST’
    121 | #define _PyVarObject_CAST(op) ((PyVarObject*)(op))
        |                                               ^~
  /home/oberstet/cpy310/include/python3.10/cpython/bytesobject.h:34:58: note: in expansion of macro ‘Py_SIZE’
     34 | #define PyBytes_GET_SIZE(op)  (assert(PyBytes_Check(op)),Py_SIZE(op))
        |                                                          ^~~~~~~
  src/compat.h:8:30: note: in expansion of macro ‘PyBytes_GET_SIZE’
      8 |       #define PyStr_GET_SIZE PyBytes_GET_SIZE
        |                              ^~~~~~~~~~~~~~~~
  src/vmp_stack.c:108:24: note: in expansion of macro ‘PyStr_GET_SIZE’
    108 |             len = (int)PyStr_GET_SIZE(frame->f_code->co_lnotab);
        |                        ^~~~~~~~~~~~~~
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for vmprof
  Running setup.py clean for vmprof
```

**Comment by om26er** [comment]
That's because Python 3.10 is currently not supported for Crossbar as mentioned in https://github.com/crossbario/crossbar/issues/1896

**Comment by om26er** [comment]
When using Python 3.10, vmprof has to be installed from master

**Comment by oberstet** [comment]
> When using Python 3.10, vmprof has to be installed from master

ahh, right, rgd py3.10, thanks for reminding;) so what should we do for a CB release?

* limit to py version <3.10 or remove vmprof from default install ?
* is there a release planned for vmprof that has ^ fix @fijal ?
* other issues rgd py 3.10 (eg there was some mention of a Mapping related issue in #1896 ..)?

**Comment by om26er** [comment]
The mapping related issue was fixed via https://github.com/crossbario/crossbar/commit/93f3931eb3fb34bae59c6a8d3d4bcbbef7131d67

The two main issues are: vmprof and cython (see traceback on the issue)

**Comment by oberstet** [comment]
rgd cython, just tried:

```
(cpy310_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ pip install cython
Collecting cython
  Using cached Cython-0.29.24-py2.py3-none-any.whl (979 kB)
Installing collected packages: cython
Successfully installed cython-0.29.24
(cpy310_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ python
Python 3.10.0 (default, Nov 24 2021, 12:27:36) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cytoolz.functoolz import *
>>> import eth_account
>>> 
```

**Comment by oberstet** [comment]
so it seems to work with vmprof from master:

```
pip install git+https://github.com/vmprof/vmprof-python.git#egg=vmprof
pip install -e .
crossbar version

(cpy310_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ crossbar version


    :::::::::::::::::
          :::::          _____                 __              _____  __
    :::::   :   :::::   / ___/______  ___ ___ / /  ___ _____  / __/ |/_/
    :::::::   :::::::  / /__/ __/ _ \(_-<(_-</ _ \/ _ `/ __/ / _/_>  <
    :::::   :   :::::  \___/_/  \___/___/___/_.__/\_,_/_/   /_/ /_/|_|
          :::::
    :::::::::::::::::   Crossbar.io FX v21.11.1 [19000101-0000000]

    Copyright (c) 2013-2021 Crossbar.io Technologies GmbH. All rights reserved.

 Crossbar.io        : 21.11.1
   txaio            : 21.2.1
   Autobahn         : 21.11.1
     UTF8 Validator : wsaccel-0.6.2
     XOR Masker     : wsaccel-0.6.2
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-1.0.2
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.16.1
     FlatBuffers    : flatbuffers-2.0
   Twisted          : 21.7.0-EPollReactor
   LMDB             : 1.2.1/lmdb-0.9.29
   Python           : 3.10.0/CPython
   PIP              : 21.3.1
   NumPy            : 1.21.4
   zLMDB            : 21.2.1
   CFXDB            : 21.2.1
   XBR              : 21.2.1
 Frozen executable  : no
 Operating system   : Linux-5.4.0-90-generic-x86_64-with-glibc2.31
 Host machine       : x86_64
 Release key        : RWT8YYDwXKYOjxxrQbsnUGFiIMKO5MDuAt+0i0s12fxM3zpfy3TCP4rU

```

**Comment by om26er** [comment]
> so it seems to work with vmprof from master:

This is gold. Having to use Crossbar with CPython 3.10 and PyPy 3.8 is going to be a great.

**Comment by oberstet** [comment]
alright, let's see if we get any feedback https://github.com/vmprof/vmprof-python/issues/240 soonish. if not, we'll remove vmprof again ...

**Comment by om26er** [comment]
hmm, we could probably ship the new release with vmprof from master, I guess that could work as well ?

**Comment by oberstet** [comment]
> we could probably ship the new release with vmprof from master, I guess that could work as well ?

yeah, changed it in the PR .. let's see what happens

we also already use own forks for 2 packages .. all of which is an annoyance, because there is no "stable wheel base" to do all the binaries building

because of above, and for repeatability, I wanted to:

1. add a wheel building step to the CI here that uploads to our server (as a wheel base store to use subsequently)
2. then, during subsequent CI steps, and for all the binaries building in particular, install CB from 1. (not PyPI)

not sure what's the status of above ... I think it might already work like this? anyways: that would solve the hassles IMO ..

**Comment by oberstet** [comment]
I've merged this now with using vmprof master .. we can wait a couple of days, for possibly vmprof doind a release, and also to add whatever smaller fixes or what still would accumulate before a release

**Comment by oberstet** [comment]
cpy 3.11 build fails with

```
      building '_vmprof' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/src
      creating build/temp.linux-x86_64-cpython-311/src/libbacktrace
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -c src/_vmprof.c -o build/temp.linux-x86_64-cpython-311/src/_vmprof.o -Wno-unused -DVMPROF_LINUX=1 -DVMPROF_UNIX=1 "-I src/" "-I src/libbacktrace"
      src/_vmprof.c: In function ‘sample_stack_now’:
      src/_vmprof.c:301:53: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
        301 |     entry_count = vmp_walk_and_record_stack(tstate->frame, m, SINGLE_BUF_SIZE/sizeof(void*)-1, (int)skip, 0);
            |                                                     ^~~~~
            |                                                     cframe
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vmprof
  Running setup.py clean for vmprof
Failed to build vmprof
```

**Pull request merged**
