### PR TITLE
Allow TCP user timeout configuration in endpoint

### LINKED ISSUE #1929: Allow TCP user timeout configuration in endpoint
TCP_USER_TIMEOUT (see man tcp) is a socket option that causes TCP connections to be closed if transmitted data is not acked within the given time (in milliseconds). This allows failing fast instead of waiting for ACKs to arrive up to 20 min on dead connections.

A use case for this is an embedded device connecting to crossbar. If this is shut down forcibly, the connection hangs and subsequent procedure registrations fail until the connection is closed. This can take up to 20 minutes.

### PR DESCRIPTION
**Pull request by Bastian-Krause**
TCP_USER_TIMEOUT (see `man tcp`) is a socket option that causes TCP connections to be closed if transmitted data is not acked within the given time (in milliseconds). This allows failing fast instead of waiting for ACKs to arrive up to 20 min on dead connections.

A use case for this is an embedded device connecting to crossbar. If this is shut down forcibly, the connection hangs and subsequent procedure registrations fail until the connection is closed. This can take up to 20 minutes.

Fixes #1929

### CODE REVIEW

**Comment by oberstet** [comment]
this looks really good and complete!

* I've unblocked the CI (first contrib) .. let's see ..
* we would need a CAA (once) .. pls see https://github.com/crossbario/crossbar/blob/master/CONTRIBUTING.md

**Comment by oberstet** [comment]
I guess the only problem the CI detects is wrong exports (__all__) ...

```
crossbar/common/twisted/sharedport.py:42:1: F822 undefined name 'SharedPort' in __all__
crossbar/common/twisted/sharedport.py:42:1: F822 undefined name 'SharedTLSPort' in __all__
```

**Comment by Bastian-Krause** [comment]
> this looks really good and complete!
> 
> * I've unblocked the CI (first contrib) .. let's see ..
> * we would need a CAA (once) .. pls see https://github.com/crossbario/crossbar/blob/master/CONTRIBUTING.md

Thanks, will look into this on Monday.

> I guess the only problem the CI detects is wrong exports (**all**) ...
> 
> ```
> crossbar/common/twisted/sharedport.py:42:1: F822 undefined name 'SharedPort' in __all__
> crossbar/common/twisted/sharedport.py:42:1: F822 undefined name 'SharedTLSPort' in __all__
> ```
> 
> as of
> 
> ```
> (cpy39_1) (base) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ find . -name "*.py" -exec grep -Hi "SharedPort" {} \;
> ./crossbar/common/twisted/endpoint.py:from crossbar.common.twisted.sharedport import SharedPort, SharedTLSPort
> ./crossbar/common/twisted/endpoint.py:            listening_port = SharedPort(port, factory, backlog, interface, reactor, shared=shared)
> ./crossbar/common/twisted/sharedport.py:__all__ = ('create_stream_socket', 'SharedPort', 'SharedTLSPort')
> ./crossbar/common/twisted/sharedport.py:class SharedPort(tcp.Port):
> ./crossbar/common/twisted/sharedport.py:class SharedTLSPort(SharedPort, ssl.Port):
> ```

Ah right, fixed.

**Comment by oberstet** [comment]
I'll wait for the CAA and will merge then! thanks again for the great work.

rgd the failing yapf ... code formatting:

```
pip install "yapf==0.29.0"
make autoformat
```

**Comment by Bastian-Krause** [comment]
I've sent the CAAs (individual + entity). All remarks should be addressed now.

**Comment by oberstet** [comment]
@Bastian-Krause thanks for the CAA! got it. and thanks for your contribution - awesome=)

**Pull request merged**
