### PR TITLE
first-cut dealer timeout/cancel implementation

### PR DESCRIPTION
**Pull request by meejah**
First hack at a timeout + cancel from the Dealer. I'm sure there are other cases to consider (like if one side or the other doesn't support cancel).

### CODE REVIEW

**Comment by oberstet** [comment]
@meejah I've prepared everything for a v20.2.1 release of CB: do you want to land this PR already or wait?

**Comment by meejah** [comment]
lets wait, and do it in the "next" release (in case of fallout etc?)

**Comment by oberstet** [comment]
> lets wait, and do it in the "next" release (in case of fallout etc?)

ok! once we have it on master, we can give it some more testing, probably also on the demo instances before pushing a new release

**Comment by meejah** [comment]
Yeah .. "should" be fairly safe as it's kind of "opt-in" by providing the new `timeout=` kwarg, but ...

**Comment by oberstet** [comment]
CI still complains: flake8 (and sphinx, I restarted that one to see if it disappears ..)

**Comment by meejah** [comment]
Hrmmm, hard to make flake8 happy: doesn't like newline before or after the `and` and also doesn't like a blackslash in there ... so I guess it has to be one line :/

Oh, the docs say there's no way to make it happy here, so I'm going with the "soon to be best practice" suggestion (and ignoring W503 in the flake8): https://www.flake8rules.com/rules/W503.html

**Pull request merged**
