### PR TITLE
Add crossbar personality namespace

### PR DESCRIPTION
**Pull request by om26er**

### CODE REVIEW

**Comment by om26er** [comment]
So this works as-is. Just clone this branch and cd to it.

```
virtualenv env
source env/bin/activate

pip3 install -r requirements.txt
pip3 uninstall enum34

pyinstaller -F bin/crossbar --add-data crossbar/personality/community/*:crossbar/personality/community/ --add-data crossbar/web/templates/*:crossbar/web/templates/ --add-data crossbar/templates/default/README.md:crossbar/templates/default --add-data crossbar/templates/default/.crossbar/*:crossbar/templates/default/.crossbar --add-data crossbar/templates/default/web/*.html:crossbar/templates/default/web --add-data crossbar/templates/default/web/js:crossbar/templates/default/web/js --add-data crossbar/keys/*:crossbar/keys

dist/crossbar init
dist/crossbar start
```

**Comment by oberstet** [comment]
here https://github.com/crossbario/crossbar/pull/1263

**Comment by oberstet** [comment]
so on linux, it seems to work now https://gist.github.com/oberstet/8ddde01a1cc9866cdb36d75a51b83e5a#file-gistfile1-txt-L53 - windows needs testing .. ;)

**Comment by om26er** [comment]
> so on linux, it seems to work now https://gist.github.com/oberstet/8ddde01a1cc9866cdb36d75a51b83e5a#file-gistfile1-txt-L53 - windows needs testing .. ;)

I am not it, just fighting some visual c++ build tools dependency issues.

**Pull request closed without merging**
