### PR TITLE
fix web config handling

### PR DESCRIPTION
**Pull request by meejah**

### CODE REVIEW

**Comment by meejah** [comment]
Ah, yes, thanks good catch! :)

**Comment by meejah** [comment]
I'm pretty sure "paths" is a dict as well (at least it is in the existing config for the Autobahn example router) and in any case the code is indexing with a ``str`` (that is ``['/']``) so it's obviously expecting a dict?

**Comment by meejah** [comment]
In any case ``x in foo` works whether foo is a list or a dict (or any collection) so it shouldn't really matter, but as far as "documenting" things dicts are more-correct ;)

**Comment by oberstet** [comment]
yeah, dict it is .. actually, any Mapping: https://github.com/crossbario/crossbar/blob/master/crossbar/common/checkconfig.py#L1729

**Comment by oddjobz** [comment]
Yeah, sorry, I was just looking at the default in the original code, looking at the surrounding code, yeah, dict .. :)

**Comment by oberstet** [comment]
I am backing this out .. it breaks stuff. The code before did work for me

**Pull request merged**
