### PR TITLE
wamp.session.get serialization

### PR DESCRIPTION
**Pull request by meejah**
Fixes https://github.com/crossbario/autobahn-python/issues/1096

### CODE REVIEW

**Comment by oberstet** [comment]
ah, this should use the marshaling code there is already, as in `return session._session_details.marshal()`

**Comment by meejah** [comment]
Hmm, `SessionDetails` doesn't have a `.marshal()` currently (in `types.py` only `SessionIdent` does currently it seems) .. but I can definitely put the code there instead..

**Comment by oberstet** [comment]
@meejah ah yes, you are right, the spec includes (optional) transport info https://wamp-proto.org/_static/gen/wamp_latest.html#wamp-session-get

IMO the best would be to "fix this once and for all" now by extending https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/types.py#L326 with transport details (consolidating the info there, instead of wherever we currently put it).

We could create a new `TransportDetails` class with a `marshal` method and have a `transport` attribute on `SessionDetails` which is an instance of the former. The `marshal` of `SessionDetails` could use the `marshal` of `TransportDetails` object.

I would leave in the attributes currently not in the spec .. maybe file an issue on wamp-proto to gather attention/consensus. Overall my main concern is to consolidate/cleanup stuff ..

**Comment by oberstet** [comment]
superseded by https://github.com/crossbario/crossbar/pull/1466

**Pull request closed without merging**
