### PR TITLE
Chunked publishes

### PR DESCRIPTION
**Pull request by meejah**
followup to #656, replaces #990

### CODE REVIEW

**Comment by oberstet** [comment]
nearly;)

The config should not be forwarded on the command line (to the forker worker process), but like this:

1. https://github.com/crossbario/crossbar/blob/master/crossbar/worker/router.py#L353 get config dict (and therein, there is the new chunk option)
2. the realm object https://github.com/crossbario/crossbar/blob/master/crossbar/worker/router.py#L384 carries the chunk option to ..
3. router_factory.start_realm https://github.com/crossbario/crossbar/blob/master/crossbar/worker/router.py#L389
4. this arrives here: https://github.com/crossbario/crossbar/blob/master/crossbar/router/router.py#L426 [note: the mqtt_payload_format there is also wrong .. that needs to be carried within the options)
5. the router (for a specific realm) carries broker/dealer, and also the options https://github.com/crossbario/crossbar/blob/master/crossbar/router/router.py#L92
6. and finally, the broker can access 5. then to do its thing

**Comment by oberstet** [comment]
so this is mostly about how to structure things to keep stuff in a coherent design ..

**Comment by meejah** [comment]
I was hoping the command-line option would be wrong :)

So since `start_router_realm` is getting the "realm" config, this is a per-realm option? (not per-router as I have in here?)

**Comment by meejah** [comment]
Okay, now getting the options via `start_router_realm`.

**Pull request merged**
