### PR TITLE
Fixed watcher restart problems

### PR DESCRIPTION
**Pull request by Kostronor**
This is a quick hacky fix for issue #490

### CODE REVIEW

**Comment by meejah** [comment]
Hi, thanks for the patch! I can't find the list of contributers, but if you've not signed something, you'll have to look at this: http://crossbar.io/docs/Contributing-to-the-project/

Otherwise, yes a timeout isn't ideal but also better than "doesn't work" ;)

**Comment by meejah** [comment]
*Ideally* I think what we'd do is send the SIGTERM (like now), wait a configurable number of seconds for the process to die and if it's still not dead, SIGKILL it. Then do the restsart. 

``_cleanup_worker`` actually does something similar to this as well, so it  might be worth factoring out code to do this (i.e. given a ``ProcessProtocol``, SIGTERM it and wait until it dies, or give up and SIGKILL it after X second and fire the returned Deferred after the process is finally dead/killed).

**Comment by Kostronor** [comment]
Hey, thanks for the heads up, will sign the CAA today (if my scanner works ;-) ) 

If I remember correctly, cleanup worker also checks every second if the process is dead now, this is highly preferred because we can have large timeouts without using the full timeout every time.

**Comment by meejah** [comment]
Yes, ``_cleanup_worker`` checks every second.
A non-polling way of accomplishing this would be even better, of course, but this works fairly well.

**Comment by oberstet** [comment]
@Kostronor CAA received - thanks! ah, and thanks for the actual patch;)

**Pull request merged**
